apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: gitbok-alerts
  namespace: gitbok
  labels:
    app: gitbok
spec:
  route:
    receiver: telegram-gitbok
    groupBy: ['alertname', 'service', 'namespace']
    groupWait: 10s
    groupInterval: 5m
    repeatInterval: 1h
    routes:
      # Watchdog heartbeat route - must be processed quickly
      - receiver: grafana-oncall-heartbeat
        matchers:
          - name: alertname
            matchType: "="
            value: GitbokWatchdog
        groupWait: 0s
        groupInterval: 1m
        repeatInterval: 50s

      # Critical alerts to Telegram
      - receiver: telegram-gitbok
        matchers:
          - name: severity
            matchType: "="
            value: critical
        groupWait: 5s
        repeatInterval: 15m

      # Warning alerts to Telegram
      - receiver: telegram-gitbok
        matchers:
          - name: severity
            matchType: "="
            value: warning
        groupWait: 30s
        repeatInterval: 30m

  receivers:
    # Telegram receiver for gitbok alerts
    - name: telegram-gitbok
      telegramConfigs:
        - botToken:
            name: gitbok-telegram-credentials
            key: bot-token
          chatID: -1002923251778  # Note: chatID must be an integer, cannot reference secret
          parseMode: HTML
          sendResolved: true
          message: |
            <b>🚨 Alert: {{ .GroupLabels.alertname }}</b>

            <b>Service:</b> {{ .GroupLabels.service }}
            <b>Namespace:</b> {{ .GroupLabels.namespace }}
            <b>Status:</b> {{ .Status }}

            {{ range .Alerts }}
            <b>Severity:</b> {{ .Labels.severity }}
            {{ if .Labels.pod }}<b>Pod:</b> {{ .Labels.pod }}{{ end }}
            <b>Summary:</b> {{ .Annotations.summary }}
            <b>Description:</b> {{ .Annotations.description }}
            {{ end }}

    # Grafana OnCall webhook (kept for compatibility)
    - name: grafana-oncall
      webhookConfigs:
        - url: https://oncall.aidbox.io/integrations/v1/alertmanager/slGWB0G7OkKeanLgCM1Jb7I8y/
          sendResolved: true

    # Grafana OnCall heartbeat for UptimeRobot
    - name: grafana-oncall-heartbeat
      webhookConfigs:
        - url: https://oncall.aidbox.io/integrations/v1/alertmanager/slGWB0G7OkKeanLgCM1Jb7I8y/heartbeat/
          sendResolved: false
