apiVersion: v1
kind: ConfigMap
metadata:
  name: gitbok-alertmanager-config
  namespace: gitbok
  labels:
    app: gitbok
data:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m

    route:
      group_by: ['alertname', 'cluster', 'service', 'namespace']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'telegram-notifications'

      routes:
        # Critical alerts for Gitbok
        - match:
            severity: critical
            service: gitbok
          receiver: 'telegram-critical'
          group_wait: 5s
          repeat_interval: 15m

        # Warning alerts for Gitbok
        - match:
            severity: warning
            service: gitbok
          receiver: 'telegram-notifications'
          group_wait: 30s
          repeat_interval: 30m

    inhibit_rules:
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'service', 'namespace']

    receivers:
      - name: 'telegram-notifications'
        telegram_configs:
          # These values should be set from Kubernetes secret
          - bot_token: '${TELEGRAM_BOT_TOKEN}'
            chat_id: ${TELEGRAM_CHAT_ID}
            parse_mode: 'HTML'
            message: |
              <b>⚠️ Alert: {{ .GroupLabels.alertname }}</b>

              <b>Service:</b> {{ .GroupLabels.service }}
              <b>Namespace:</b> {{ .GroupLabels.namespace }}
              <b>Status:</b> {{ .Status }}

              {{ range .Alerts }}
              <b>Severity:</b> {{ .Labels.severity }}
              <b>Pod:</b> {{ .Labels.pod }}
              <b>Summary:</b> {{ .Annotations.summary }}
              <b>Description:</b> {{ .Annotations.description }}

              <b>Labels:</b>
              {{ range $key, $value := .Labels }}
                • {{ $key }}: {{ $value }}
              {{ end }}
              {{ end }}

      - name: 'telegram-critical'
        telegram_configs:
          - bot_token: '${TELEGRAM_BOT_TOKEN}'
            chat_id: ${TELEGRAM_CHAT_ID}
            parse_mode: 'HTML'
            message: |
              <b>🚨🚨 CRITICAL ALERT 🚨🚨</b>
              <b>{{ .GroupLabels.alertname }}</b>

              <b>Service:</b> {{ .GroupLabels.service }}
              <b>Namespace:</b> {{ .GroupLabels.namespace }}

              {{ range .Alerts }}
              <b>Pod:</b> {{ .Labels.pod }}
              <b>{{ .Annotations.summary }}</b>
              {{ .Annotations.description }}

              Time: {{ .StartsAt.Format "15:04:05 MST" }}
              {{ end }}

              <b>IMMEDIATE ACTION REQUIRED!</b>