    %% NODE STYLES - RED COLOR VARIATIONS
    classDef red1 fill:#fef2f2,stroke:#F58685,stroke-width:1px,color:#1D2331
    classDef red2 fill:#fef2f2,stroke:#F58685,stroke-width:2px,color:#1D2331
    classDef red3 fill:#fef2f2,stroke:#F58685,stroke-width:3px,color:#1D2331
    %% NODE STYLES - BLUE COLOR VARIATIONS
    classDef blue1 fill:#eff6ff,stroke:#7DA1EF,stroke-width:1px,color:#1D2331
    classDef blue2 fill:#eff6ff,stroke:#7DA1EF,stroke-width:2px,color:#1D2331
    classDef blue3 fill:#eff6ff,stroke:#7DA1EF,stroke-width:3px,color:#1D2331
    %% NODE STYLES - VIOLET COLOR VARIATIONS
    classDef violet1 fill:#faf5ff,stroke:#AB8AE3,stroke-width:1px,color:#1D2331
    classDef violet2 fill:#faf5ff,stroke:#AB8AE3,stroke-width:2px,color:#1D2331
    classDef violet3 fill:#faf5ff,stroke:#AB8AE3,stroke-width:3px,color:#1D2331
    %% NODE STYLES - GREEN COLOR VARIATIONS
    classDef green1 fill:#f0fdf4,stroke:#78B58E,stroke-width:1px,color:#1D2331
    classDef green2 fill:#f0fdf4,stroke:#78B58E,stroke-width:2px,color:#1D2331
    classDef green3 fill:#f0fdf4,stroke:#78B58E,stroke-width:3px,color:#1D2331
    %% NODE STYLES - YELLOW COLOR VARIATIONS
    classDef yellow1 fill:#fefce8,stroke:#E4BE6F,stroke-width:1px,color:#1D2331
    classDef yellow2 fill:#fefce8,stroke:#E4BE6F,stroke-width:2px,color:#1D2331
    classDef yellow3 fill:#fefce8,stroke:#E4BE6F,stroke-width:3px,color:#1D2331
    %% NODE STYLES - NEUTRAL COLOR VARIATIONS
    classDef neutral1 fill:#F5F5F6,stroke:#CCCED3,stroke-width:1px,color:#1D2331
    classDef neutral2 fill:#F5F5F6,stroke:#CCCED3,stroke-width:2px,color:#1D2331
    classDef neutral3 fill:#F5F5F6,stroke:#CCCED3,stroke-width:3px,color:#1D2331
    %% LINK LABEL STYLES
    classDef linkLabelNeutral fill:#F5F5F6,stroke:#CCCED3,stroke-width:1px,color:#1D2331
    classDef linkLabelSuccess fill:#f0fdf4,stroke:#16a34a,stroke-width:1px,color:#1D2331
    classDef linkLabelError fill:#fef2f2,stroke:#dc2626,stroke-width:1px,color:#1D2331
