apiVersion: v1
kind: Service
metadata:
  name: meilisearch
  namespace: gitbok
spec:
  type: ClusterIP
  selector:
    app: meilisearch
  ports:
  - name: http
    port: 7700
    targetPort: 7700
    protocol: TCP