apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: meilisearch-monitor
  namespace: gitbok
  labels:
    app: meilisearch
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: meilisearch

  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      authorization:
        credentials:
          name: meilisearch-secret
          key: master-key
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_name]
          targetLabel: pod
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: node
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: namespace
        - sourceLabels: [__meta_kubernetes_service_name]
          targetLabel: service
      metricRelabelings:
        # Add instance label based on pod name
        - sourceLabels: [pod]
          targetLabel: instance
          regex: (.+)
          replacement: ${1}
