root-redirect: "/aidbox"

products:
  - id: aidbox
    name: "Aidbox Uses Docs"
    # url <BASE_URL><DOCS_PREFIX>/aidbox
    path: /aidbox
    config: ./aidbox/.gitbook.yaml
    logo: .gitbook/assets/aidbox_logo.jpg
    favicon: .gitbook/assets/favicon.ico
    links:
      - text: "Run Aidbox locally"
        href: "/getting-started/run-aidbox-locally"
      - text: "Run Aidbox in Sandbox"
        href: "/getting-started/run-aidbox-in-sandbox"
      - text: "Talk to us"
        href: "https://bit.ly/3R7eLke"
        target: "_blank"
      - text: "Ask community"
        href: "https://connect.health-samurai.io/"
        target: "_blank"

  - id: forms
    name: "Forms Documentation"
    # url <BASE_URL><DOCS_PREFIX>/forms
    path: /forms
    config: ./forms/.gitbook.yaml
    logo: .gitbook/assets/aidbox_logo.jpg
    favicon: .gitbook/assets/favicon.ico
    links:
      - text: "Getting Started"
        href: "/getting-started"
      - text: "Forms Gallery"
        href: "/gallery"
      - text: "Contact Support"
        href: "https://example.com/support"
        target: "_blank"
      - text: "Forms Community"
        href: "https://example.com/community"
        target: "_blank"
