---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitbok
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: gitbok
  timeout: 5m0s
  # recurseSubmodules: true
  url: ssh://git@github.com/HealthSamurai/documentation.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitbok
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitbok
