---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: gitbok
  namespace: flux-system
spec:
  image: ghcr.io/healthsamurai/documentation
  interval: 1m
  provider: generic
